#!/bin/sh
set -e
perl="$1"

cpopt=''
touch cptest
if cp -l cptest cptestout 2>/dev/null; then
  cpopt='-l'
fi
rm -f cptest cptestout

tempdir="$(mktemp -d perlXXXXX)"
cp -R $cpopt "$PERLBREW_ROOT/perls/$perl/" "$tempdir/"
(
  echo "Perl $perl built by Travis Helpers: $(git --git-dir="$HELPER_ROOT/.git" describe --all --long HEAD)"
  echo '------------------------------------------------------------------------------'
  "$PERLBREW_ROOT/perls/$perl/bin/perl" -v
  echo '------------------------------------------------------------------------------'
  if [ -e /etc/lsb-release ]; then
    echo '------------------------------------------------------------------------------'
    cat /etc/lsb-release
  fi
) > "$tempdir/README"
git add -f "$tempdir"
tree="$(git write-tree --prefix="$tempdir/")"
git reset -q -- "$tempdir"
rm -rf "$tempdir"
export GIT_AUTHOR_NAME="$(git log -n 1 --format='%an')"
export GIT_AUTHOR_EMAIL="$(git log -n 1 --format='%ae')"
export GIT_COMMITTER_NAME="Travis CI"
export GIT_COMMITTER_EMAIL="travis-ci@$(hostname -f)"
parent="$(git rev-parse -q --verify refs/heads/perl-$perl || true)"
if [ -z "$parent" ]; then
  parent="$(git ls-remote origin refs/heads/perl-$perl | cut -f 1)"
fi
if [ -n "$parent" ]; then
  parent="-p $parent"
fi
ref="$(git --git-dir="$HELPER_ROOT/.git" describe --all --long HEAD)"
commit="$(git commit-tree "$tree" $parent -m "Perl $perl built for $ref")"
git update-ref "refs/heads/perl-$perl" "$commit"
echo "Committed $(git describe --all --long perl-$perl)"
