#!/bin/bash
set -e
perl_version="${1/@*/}"
bare_version="${perl_version/-*/}"
local_lib="${1/*@/}"
[ "$local_lib" == "$1" ] && unset local_lib
shift

declare -a variants

if [ "$bare_version" != "$perl_version" ]; then
  variants=("$perl_version")
else
  declare -a defaults
  while read version variant; do
    full="$perl_version"
    if [ "$variant" != "-" ]; then
      full+="-$variant"
    fi
    if [ "$version" == "*" ]; then
      defaults+=("$full")
    elif [ "$version" == "$perl_version" ]; then
      variants+=("$full")
    fi
  done < variants.txt

  if [ "${#variants[@]}" == "0" ]; then
    variants=("${defaults[@]}")
  fi
fi

for variant in "${variants[@]}"; do
  "$@" "$variant"
done
