#!/bin/bash
set -e

declare -a branches
for arg; do
  local_lib="${arg/*@/}"
  [ "$local_lib" == "$arg" ] && unset local_lib
  perl_version="${arg/@*/}"
  branches+=("perl/$perl_version")
  if [ -n "$local_lib" ]; then
    branches+=("libs/$perl_version/$local_lib")
  fi
done

if [ ! -e id_rsa.dec ]; then
  cp id_rsa id_rsa.dec
  chmod 600 id_rsa.dec
  ssh-keygen -p -f id_rsa.dec -P "$SSH_KEY_PASS" -N '' || rm id_rsa.dec
fi

git config --replace-all url.git@github.com:.pushInsteadOf git://github.com/ '^git://github\.com/$'
git config --replace-all url.git@github.com:.pushInsteadOf https://github.com/ '^https://github\.com/$'

GIT_SSH=./ssh-wrapper git push origin "${branches[@]}"
