#!/bin/bash
set -e

function log_err {
  local logfile="$(mktemp -t run-log-XXXXXX)"
  "$@" 2>&1 > "$logfile" && return 0
  local status="$?"
  cat "$logfile" 1>&2
  rm "$logfile"
  return "$status"
}

cd "$( dirname "$0" )"

log_err git pull
log_err git checkout .travis.yml

# yep, i'm regexing html and there's nothing you can do about it
latest="$(
  curl -s http://www.cpan.org/src/5.0/ \
  | perl -nle'
    push @f, [$1,$2]
      if /href="perl-(5\.([1-9]?[13579]\.[1-9][0-9]*))\.tar\.gz"/;
    END {
      my $v = (sort { $b->[1] <=> $a->[1] } @f)[0][0];
      print $v;
    }
  '
)"

if [ -z "$latest" ]; then
  echo "Unable to find latest dev release!" 1>&2
  exit 1
fi

dev="$(perl -ne'print $1 if /^# dev perl\b/../# end dev perl\b/ and  /^\s*-\s*"?([0-9.]+)"?$/' .travis.yml)"

if [ "$dev" = "$latest" ]; then
  log_err git push origin master
  exit 0
fi

perl -i -ne'
  if (1../# dev perl\b/) {
    print;
    if (/# dev perl\b/) {
      print qq{  - "'$latest'"\n};
      print qq{  - "'$latest'-thr"\n};
    }
  }
  elsif (/# end dev perl\b/..0) {
    print;
  }
' .travis.yml

export GIT_AUTHOR_NAME="Automatic Dev Perl Updates"
export GIT_AUTHOR_EMAIL='autobuild@autobuild'
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"

log_err git add .travis.yml
log_err git commit -m"update dev perl to $latest"
log_err git push origin master
